// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"goblog.com/pkg/database"
	"goblog.com/pkg/environment"
	"goblog.com/pkg/logger"
	"goblog.com/service/feedback/internal/application"
	"goblog.com/service/feedback/internal/config"
)

// Injectors from wire.go:

func InitApplication(conf string) (*application.Application, func(), error) {
	configConfig, err := config.NewConfig(conf)
	if err != nil {
		return nil, nil, err
	}
	dsnString := providerDatabase(configConfig)
	v := providerDatabaseOption(configConfig)
	databaseDatabase, err := database.NewDatabase(dsnString, v...)
	if err != nil {
		return nil, nil, err
	}
	v2 := providerLoggerOption(configConfig)
	zapLogger, cleanup, err := logger.NewLogger(v2...)
	if err != nil {
		return nil, nil, err
	}
	applicationApplication, err := application.NewApplication(databaseDatabase, zapLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return applicationApplication, func() {
		cleanup()
	}, nil
}

// wire.go:

func providerLoggerOption(config2 *config.Config) []logger.Option {
	return []logger.Option{logger.WithEnv(environment.Environment(config2.App.Env))}
}

func providerDatabase(config2 *config.Config) database.DSNString {
	return database.ProviderDSNString(config2.Mysql.DSN)
}

func providerDatabaseOption(config2 *config.Config) []database.Option {
	return []database.Option{database.WithEnv(environment.Environment(config2.App.Env))}
}
