app:
  name: article
  env: local # local, testing, production
  debug: true
server:
  http-addr: 127.0.0.1:50051
  grpc-addr: 127.0.0.1:8051
mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/up?charset=utf8mb4&parseTime=true&multiStatements=true
