// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: usertag_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserTagServiceClient is the client API for UserTagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserTagServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*UserTagId, error)
	Get(ctx context.Context, in *UserIdWithUserTagId, opts ...grpc.CallOption) (*UserTag, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*RowsAffected, error)
	Delete(ctx context.Context, in *UserIdWithUserTagId, opts ...grpc.CallOption) (*RowsAffected, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type userTagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserTagServiceClient(cc grpc.ClientConnInterface) UserTagServiceClient {
	return &userTagServiceClient{cc}
}

func (c *userTagServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*UserTagId, error) {
	out := new(UserTagId)
	err := c.cc.Invoke(ctx, "/usertag_service.v1.UserTagService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userTagServiceClient) Get(ctx context.Context, in *UserIdWithUserTagId, opts ...grpc.CallOption) (*UserTag, error) {
	out := new(UserTag)
	err := c.cc.Invoke(ctx, "/usertag_service.v1.UserTagService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userTagServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*RowsAffected, error) {
	out := new(RowsAffected)
	err := c.cc.Invoke(ctx, "/usertag_service.v1.UserTagService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userTagServiceClient) Delete(ctx context.Context, in *UserIdWithUserTagId, opts ...grpc.CallOption) (*RowsAffected, error) {
	out := new(RowsAffected)
	err := c.cc.Invoke(ctx, "/usertag_service.v1.UserTagService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userTagServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/usertag_service.v1.UserTagService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserTagServiceServer is the server API for UserTagService service.
// All implementations must embed UnimplementedUserTagServiceServer
// for forward compatibility
type UserTagServiceServer interface {
	Create(context.Context, *CreateRequest) (*UserTagId, error)
	Get(context.Context, *UserIdWithUserTagId) (*UserTag, error)
	Update(context.Context, *UpdateRequest) (*RowsAffected, error)
	Delete(context.Context, *UserIdWithUserTagId) (*RowsAffected, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedUserTagServiceServer()
}

// UnimplementedUserTagServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserTagServiceServer struct {
}

func (UnimplementedUserTagServiceServer) Create(context.Context, *CreateRequest) (*UserTagId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserTagServiceServer) Get(context.Context, *UserIdWithUserTagId) (*UserTag, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUserTagServiceServer) Update(context.Context, *UpdateRequest) (*RowsAffected, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserTagServiceServer) Delete(context.Context, *UserIdWithUserTagId) (*RowsAffected, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserTagServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedUserTagServiceServer) mustEmbedUnimplementedUserTagServiceServer() {}

// UnsafeUserTagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserTagServiceServer will
// result in compilation errors.
type UnsafeUserTagServiceServer interface {
	mustEmbedUnimplementedUserTagServiceServer()
}

func RegisterUserTagServiceServer(s grpc.ServiceRegistrar, srv UserTagServiceServer) {
	s.RegisterService(&UserTagService_ServiceDesc, srv)
}

func _UserTagService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTagServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usertag_service.v1.UserTagService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTagServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserTagService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdWithUserTagId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTagServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usertag_service.v1.UserTagService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTagServiceServer).Get(ctx, req.(*UserIdWithUserTagId))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserTagService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTagServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usertag_service.v1.UserTagService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTagServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserTagService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdWithUserTagId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTagServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usertag_service.v1.UserTagService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTagServiceServer).Delete(ctx, req.(*UserIdWithUserTagId))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserTagService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTagServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usertag_service.v1.UserTagService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTagServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserTagService_ServiceDesc is the grpc.ServiceDesc for UserTagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserTagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usertag_service.v1.UserTagService",
	HandlerType: (*UserTagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserTagService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserTagService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserTagService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserTagService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserTagService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usertag_service.proto",
}
