app:
  env: local # local, testing, production
  debug: true
  locale: zh-CN

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  database: up
  username: root
  password: 123456
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
