app:
  name: search
  env: local # local, testing, production
  debug: true
database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  database: up
  username: root
  password: 123456
elasticsearch:
  addrs:
    - 127.0.0.1:9200