// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: example_service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ExampleRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ExampleRequest) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ExampleRequestValidationError is the validation error returned by
// ExampleRequest.Validate if the designated constraints aren't met.
type ExampleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExampleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExampleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExampleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExampleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExampleRequestValidationError) ErrorName() string { return "ExampleRequestValidationError" }

// Error satisfies the builtin error interface
func (e ExampleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExampleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExampleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExampleRequestValidationError{}

// Validate checks the field values on ExampleResponse with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *ExampleResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// ExampleResponseValidationError is the validation error returned by
// ExampleResponse.Validate if the designated constraints aren't met.
type ExampleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExampleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExampleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExampleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExampleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExampleResponseValidationError) ErrorName() string { return "ExampleResponseValidationError" }

// Error satisfies the builtin error interface
func (e ExampleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExampleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExampleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExampleResponseValidationError{}

// Validate checks the field values on ExampleValidateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ExampleValidateRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetName()) < 2 {
		return ExampleValidateRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 2 runes",
		}
	}

	if m.GetAge() <= 0 {
		return ExampleValidateRequestValidationError{
			field:  "Age",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// ExampleValidateRequestValidationError is the validation error returned by
// ExampleValidateRequest.Validate if the designated constraints aren't met.
type ExampleValidateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExampleValidateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExampleValidateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExampleValidateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExampleValidateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExampleValidateRequestValidationError) ErrorName() string {
	return "ExampleValidateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExampleValidateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExampleValidateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExampleValidateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExampleValidateRequestValidationError{}
