// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: userpost.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on UserPost with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserPost) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for Status

	if v, ok := interface{}(m.GetPublishedTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserPostValidationError{
				field:  "PublishedTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserPostValidationError{
				field:  "UpdatedTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Sort

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserPostValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserPostValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// UserPostValidationError is the validation error returned by
// UserPost.Validate if the designated constraints aren't met.
type UserPostValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserPostValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserPostValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserPostValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserPostValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserPostValidationError) ErrorName() string { return "UserPostValidationError" }

// Error satisfies the builtin error interface
func (e UserPostValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserPost.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserPostValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserPostValidationError{}

// Validate checks the field values on UserPostId with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *UserPostId) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// UserPostIdValidationError is the validation error returned by
// UserPostId.Validate if the designated constraints aren't met.
type UserPostIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserPostIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserPostIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserPostIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserPostIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserPostIdValidationError) ErrorName() string { return "UserPostIdValidationError" }

// Error satisfies the builtin error interface
func (e UserPostIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserPostId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserPostIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserPostIdValidationError{}

// Validate checks the field values on UserIdWithUserPostId with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *UserIdWithUserPostId) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for Id

	return nil
}

// UserIdWithUserPostIdValidationError is the validation error returned by
// UserIdWithUserPostId.Validate if the designated constraints aren't met.
type UserIdWithUserPostIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserIdWithUserPostIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserIdWithUserPostIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserIdWithUserPostIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserIdWithUserPostIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserIdWithUserPostIdValidationError) ErrorName() string {
	return "UserIdWithUserPostIdValidationError"
}

// Error satisfies the builtin error interface
func (e UserIdWithUserPostIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserIdWithUserPostId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserIdWithUserPostIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserIdWithUserPostIdValidationError{}

// Validate checks the field values on RowsAffected with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *RowsAffected) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for RowsAffected

	return nil
}

// RowsAffectedValidationError is the validation error returned by
// RowsAffected.Validate if the designated constraints aren't met.
type RowsAffectedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RowsAffectedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RowsAffectedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RowsAffectedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RowsAffectedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RowsAffectedValidationError) ErrorName() string { return "RowsAffectedValidationError" }

// Error satisfies the builtin error interface
func (e RowsAffectedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRowsAffected.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RowsAffectedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RowsAffectedValidationError{}

// Validate checks the field values on CreateUserPost with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CreateUserPost) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	if utf8.RuneCountInString(m.GetTitle()) > 255 {
		return CreateUserPostValidationError{
			field:  "Title",
			reason: "value length must be at most 255 runes",
		}
	}

	if l := utf8.RuneCountInString(m.GetContent()); l < 1 || l > 255 {
		return CreateUserPostValidationError{
			field:  "Content",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
	}

	if _, ok := UserPostStatus_name[int32(m.GetStatus())]; !ok {
		return CreateUserPostValidationError{
			field:  "Status",
			reason: "value must be one of the defined enum values",
		}
	}

	if v, ok := interface{}(m.GetPublishedTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateUserPostValidationError{
				field:  "PublishedTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateUserPostValidationError{
				field:  "UpdatedTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetSort() < 0 {
		return CreateUserPostValidationError{
			field:  "Sort",
			reason: "value must be greater than or equal to 0",
		}
	}

	return nil
}

// CreateUserPostValidationError is the validation error returned by
// CreateUserPost.Validate if the designated constraints aren't met.
type CreateUserPostValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserPostValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserPostValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserPostValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserPostValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserPostValidationError) ErrorName() string { return "CreateUserPostValidationError" }

// Error satisfies the builtin error interface
func (e CreateUserPostValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserPost.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserPostValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserPostValidationError{}

// Validate checks the field values on UpdateUserPost with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *UpdateUserPost) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for Status

	if v, ok := interface{}(m.GetPublishedTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateUserPostValidationError{
				field:  "PublishedTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateUserPostValidationError{
				field:  "UpdatedTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Sort

	return nil
}

// UpdateUserPostValidationError is the validation error returned by
// UpdateUserPost.Validate if the designated constraints aren't met.
type UpdateUserPostValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserPostValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserPostValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserPostValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserPostValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserPostValidationError) ErrorName() string { return "UpdateUserPostValidationError" }

// Error satisfies the builtin error interface
func (e UpdateUserPostValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserPost.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserPostValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserPostValidationError{}

// Validate checks the field values on UpdateSortRequest with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *UpdateSortRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for SortType

	// no validation rules for Sort

	return nil
}

// UpdateSortRequestValidationError is the validation error returned by
// UpdateSortRequest.Validate if the designated constraints aren't met.
type UpdateSortRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSortRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSortRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSortRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSortRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSortRequestValidationError) ErrorName() string {
	return "UpdateSortRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSortRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSortRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSortRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSortRequestValidationError{}

// Validate checks the field values on ListRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ListRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for UserId

	// no validation rules for Page

	// no validation rules for PerPage

	// no validation rules for Keyword

	return nil
}

// ListRequestValidationError is the validation error returned by
// ListRequest.Validate if the designated constraints aren't met.
type ListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRequestValidationError) ErrorName() string { return "ListRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRequestValidationError{}

// Validate checks the field values on ListResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ListResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Total

	// no validation rules for PerPage

	// no validation rules for CurrentPage

	// no validation rules for LastPage

	// no validation rules for From

	// no validation rules for To

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListResponseValidationError is the validation error returned by
// ListResponse.Validate if the designated constraints aren't met.
type ListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListResponseValidationError) ErrorName() string { return "ListResponseValidationError" }

// Error satisfies the builtin error interface
func (e ListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListResponseValidationError{}
