// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"goblog.com/pkg/environment"
	"goblog.com/pkg/gin"
	"goblog.com/pkg/logger"
	"goblog.com/web/app/article"
	"goblog.com/web/app/book"
	"goblog.com/web/pkg/application"
)

// Injectors from wre.go:

func InitApplication() (*application.Application, func(), error) {
	v := ginOption()
	engine, err := gin.NewGin(v...)
	if err != nil {
		return nil, nil, err
	}
	options := logger.NewOptions()
	zapLogger, cleanup, err := logger.NewLogger(options)
	if err != nil {
		return nil, nil, err
	}
	articleArticle := article.NewArticle(engine, zapLogger)
	bookBook := book.NewBook(engine, zapLogger)
	applicationApplication := application.NewApplication(engine, zapLogger, articleArticle, bookBook)
	return applicationApplication, func() {
		cleanup()
	}, nil
}

// wre.go:

var providerSet = wire.NewSet(application.ProviderSet, wire.NewSet(gin.ProviderSet, ginOption), logger.ProviderSet, article.ProviderSet, book.ProviderSet,
)

func ginOption() []gin.Option {
	return []gin.Option{gin.WithEnv(environment.DEVELOPMENT)}
}
